### ISSUE TITLE
BUG - [missing PVBUTLER

### ISSUE THREAD

**Issue by overijse** [muppet3000/growatt_server_hacs#45]
**Describe the bug**

missing pvbutler:
server.pvbutler.com 

SERVER_URLS = [
    "https://openapi.growatt.com/",
    "https://server-api.growatt.com/",
    "https://server.growatt.com/",
    "https://server-us.growatt.com/",
    "http://server.smten.com/",
    "https://pvplusanz.jinkosolar.com/",
]

-->

**Growatt Device Type**

Device(s): 

**Home Assistant information**
 - Home Assistant version:  last one
 - Growatt Server API Integration version: last one
-->

**Comment by muppet3000** [comment]
I've just made a push to the 'dev' branch with this change, please would you try running this version in HACS and let me know if it has added as you'd expect?

**Comment by overijse** [comment]
Thank you Chris for the fast help. It is working. kind regards, Pierre

**Comment by overijse** [comment]
Thank you Chris,

Pierre

**Comment by muppet3000** [comment]
I'll do a formal release with this in it for you so you don't have to run from Dev

**Comment by muppet3000** [comment]
Now present in the 1.0.4 release

**Comment by overijse** [comment]
Thank you Chris
