### ISSUE TITLE
BUG - Account blocked both on HA integration and on the mobile app

### ISSUE THREAD

**Issue by jeroenloopstra** [muppet3000/growatt_server_hacs#48]
**Describe the bug**
Every morning, I'm being locked on my growatt account on the app. Also HA does not show any data. Between 10-11 I can login again and HA is also receiving data. Web application still works for login, so I can check that there is data but just not receiving it in HA

**To Reproduce**

1. Connect HA with Growatt via HACS application
2. Try to login with mobile app in the morning
3. Get account is blocked notification
4. Also see that HA is not receiving data
5. Check web application and see that data is there

**Growatt Device Type**

Device(s): 
NACACLR48Z

**Home Assistant information**
 - Home Assistant version: 11.2
 - Growatt Server API Integration version: 1.0.4

**Comment by jeroenloopstra** [comment]
Not sure if more users have this, but it's related to the polling from HA if I read the interwebs. If possible, would be great if this can be reduced, with the integration still working

**Comment by muppet3000** [comment]
This is a known issue, it's highlighted on the main home page for this github.

**Comment by jeroenloopstra** [comment]
Ok sorry I missed that, I'll close this one
